import sqlite3
import json
import random
import datetime

def run(conn):
    cursor = conn.cursor()
    rbac_namespaces = ['general', 'platform_incidents', 'cloud_observability', 'genai_platform', 'release_management']
    chunk_strategies = ['recursive_splitter', 'simple_splitter']
    titles = [
        "Incident Management Runbook", "Azure Monitoring Playbook", "RAG Architecture Overview",
        "Onboarding Guide for SREs", "Production Readiness Checklist", "Service Degradation RCA",
        "Synthetic Test Plan", "Security Audit Summary", "API Reference Documentation",
        "Root Cause Analysis Template"
    ]
    authors = ["Souvik", "Cloud SRE Team", "AI Platform", "HR Tech", "Platform Engineering", "SecurityOps", "DevOps Admin"]
    sources = ["Confluence", "SharePoint", "GitHub", "Notion", "Google Drive"]
    
    for i in range(50):
        doc_id = f"DOC_{1000 + i}"
        title = random.choice(titles)
        author = random.choice(authors)
        source = random.choice(sources)
        summary = f"{title} autogenerated summary paragraph for document {doc_id}."
        rbac_namespace = random.choice(rbac_namespaces)
        chunk_strategy = random.choice(chunk_strategies)
        chunk_size_char = random.choice([512, 768, 1024])
        overlap_char = random.choice([50, 80, 120])
        # Metadata JSON structure
        metadata_json = json.dumps({
            "categories": [random.choice(["runbook", "architecture", "checklist", "guide", "reference"])],
            "keywords": random.sample(["incidents", "cloud", "monitoring", "RAG", "SRE", "production", "release", "security", "api", "root cause"], 3),
            "doc_type": random.choice(["runbook", "playbook", "design_spec", "guide", "checklist", "report"]),
            "created_date": (datetime.datetime.now() - datetime.timedelta(days=random.randint(0, 365))).strftime("%Y-%m-%d"),
            "tags": random.sample(["critical", "prod", "analysis", "audit", "synthetic", "onboarding", "reference"], 2)
        })
        # last_ingested can default to CURRENT_TIMESTAMP
        cursor.execute('''
            INSERT OR IGNORE INTO document_metadata (
                doc_id, title, author, source, summary, rbac_namespace,
                chunk_strategy, chunk_size_char, overlap_char, metadata_json
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            doc_id, title, author, source, summary, rbac_namespace,
            chunk_strategy, chunk_size_char, overlap_char, metadata_json
        ))
    conn.commit()
